2021-07-15 07:02:13,158 INFO 84143 [egg-logrotator] agent logger reload: got log-reload message
2021-07-15 07:15:07,680 ERROR 84143 nodejs.ClusterClientNoResponseError: client no response in 754556ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 84143
hostname: hemiao.local

2021-07-15 08:31:04,368 ERROR 84143 nodejs.ClusterClientNoResponseError: client no response in 4555868ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 84143
hostname: hemiao.local

2021-07-15 09:11:31,069 ERROR 84143 nodejs.ClusterClientNoResponseError: client no response in 652714ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 84143
hostname: hemiao.local

