2021-07-07 00:03:07,729 INFO 21502 [egg-logrotator] agent logger reload: got log-reload message
2021-07-07 01:51:17,351 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 6489619ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 03:39:27,245 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 6489773ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 05:27:38,270 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 6490874ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 07:12:18,214 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 6279843ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 07:30:07,252 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 1048885ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 08:33:20,137 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 3792084ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 11:36:47,869 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 466285ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 11:42:53,109 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 325141ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 11:49:46,214 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 279974ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 11:53:23,579 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 176576ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 12:00:05,345 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 361734ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 12:11:29,020 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 202825ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 12:42:35,570 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 1825744ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 13:09:37,501 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 1521125ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 13:25:31,516 ERROR 21502 nodejs.ClusterClientNoResponseError: client no response in 333886ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 21502
hostname: 192.168.0.104

2021-07-07 17:39:58,855 INFO 74183 [egg:logger] init all loggers with options: {"dir":"/Users/hemiao/Desktop/项目/h5-mall/server/logs/server","encoding":"utf8","env":"local","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":false,"outputJSON":false,"buffer":true,"appLogName":"server-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{"consoleLevel":"WARN"},"allowDebugAtProd":false,"type":"agent"}
2021-07-07 17:39:58,864 INFO 74183 [egg:core] dump config after load, 5ms
2021-07-07 17:39:58,939 INFO 74183 [egg-watcher] Start watching: ["/Users/hemiao/Desktop/项目/h5-mall/server/app","/Users/hemiao/Desktop/项目/h5-mall/server/config","/Users/hemiao/Desktop/项目/h5-mall/server/mocks","/Users/hemiao/Desktop/项目/h5-mall/server/mocks_proxy","/Users/hemiao/Desktop/项目/h5-mall/server/app.js"]
2021-07-07 17:39:58,939 INFO 74183 [egg-watcher] Start watching: "/Users/hemiao/Desktop/项目/h5-mall/server/app"
2021-07-07 17:39:58,939 INFO 74183 [egg-watcher] Start watching: "/Users/hemiao/Desktop/项目/h5-mall/server/config"
2021-07-07 17:39:58,939 INFO 74183 [egg-watcher] Start watching: "/Users/hemiao/Desktop/项目/h5-mall/server/mocks"
2021-07-07 17:39:58,939 INFO 74183 [egg-watcher] Start watching: "/Users/hemiao/Desktop/项目/h5-mall/server/mocks_proxy"
2021-07-07 17:39:58,939 INFO 74183 [egg-watcher] Start watching: "/Users/hemiao/Desktop/项目/h5-mall/server/app.js"
2021-07-07 17:39:58,942 INFO 74183 [egg-watcher:agent] watcher start success
2021-07-07 17:39:58,967 INFO 74183 [egg:core] dump config after ready, 7ms
2021-07-07 19:03:52,173 ERROR 74183 nodejs.ClusterClientNoResponseError: client no response in 89925ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 74183
hostname: hemiao.local

2021-07-07 19:18:52,483 ERROR 74183 nodejs.ClusterClientNoResponseError: client no response in 880284ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 74183
hostname: hemiao.local

2021-07-07 19:33:54,485 ERROR 74183 nodejs.ClusterClientNoResponseError: client no response in 901998ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 74183
hostname: hemiao.local

2021-07-07 19:48:55,483 ERROR 74183 nodejs.ClusterClientNoResponseError: client no response in 900995ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 74183
hostname: hemiao.local

2021-07-07 20:01:53,832 ERROR 74183 nodejs.ClusterClientNoResponseError: client no response in 777564ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 74183
hostname: hemiao.local

2021-07-07 21:21:30,372 ERROR 74183 nodejs.ClusterClientNoResponseError: client no response in 4756513ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 74183
hostname: hemiao.local

2021-07-07 23:10:16,508 ERROR 74183 nodejs.ClusterClientNoResponseError: client no response in 6086071ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 74183
hostname: hemiao.local

2021-07-07 23:29:00,490 ERROR 74183 nodejs.ClusterClientNoResponseError: client no response in 1123975ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 74183
hostname: hemiao.local

2021-07-08 01:00:19,507 ERROR 74183 nodejs.ClusterClientNoResponseError: client no response in 5478716ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/hemiao/Desktop/项目/h5-mall/server/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 74183
hostname: hemiao.local

